services:
  ninjanex_backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "3001"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ninjanex_backend
    ports:
      - "80:80"
